<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Expense as Model;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [ ['code' => 'SAR'], ['name' => 'SMU Airlines', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'HSR'], ['name' => 'Handling SMU / RA Charges', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'DLO'], ['name' => 'Delivery Only', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'PCO'], ['name' => 'Pickup Only', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'PCD'], ['name' => 'Pickup & Delivery', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'CSL'], ['name' => 'Consolidator', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'MBG'], ['name' => 'MBG (Damage/Missing)', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'SHH'], ['name' => 'SHCP/Handcarry Handling', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'TMK'], ['name' => 'Tagihan Mitra Kurir (Insentif Bulanan)', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'RVN'], ['name' => 'Rental Van', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'TLH'], ['name' => 'Trucking Line Haul', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
            [ ['code' => 'MNL'], ['name' => 'Manual', 'columns' => [
                'withholding_tax'               => true,
                'tax_code'                      => true,
                'coa_product'                   => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'cost_area'                     => true,
                'cost_center'                   => true,
                'no_smu'                        => true,
                'route_smu'                     => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'awb_rpx'                       => true,
                'service_rpx'                   => true,
                'sales_channel'                 => true,
                'route_awb'                     => true,
                'dist_code'                     => true,
                'line_number_oracle'            => true,
                'scan_status'                   => true,
                'validation_smu_awb'            => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_invoice'            => true,
            ] ]],
        ];

        foreach($data as $row) {
            Model::updateOrCreate(
                $row[0],
                $row[1],
            );
        }
    }
}
