<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Expense as Model;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [ ['code' => 'SAR'], ['mandatory_scan' => 'SMU&GLO','name' => 'SMU Airlines', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'smu'                           => true,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'HSR'], ['mandatory_scan' => 'GLO','name' => 'Handling SMU / RA Charges', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => true,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => true,
                'smu'                           => true,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'DLO'], ['mandatory_scan' => 'HOV&POD','name' => 'Delivery Only', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'PCO'], ['mandatory_scan' => 'PUP/PUX','name' => 'Pickup Only', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'PCD'], ['mandatory_scan' => '(PUP/PUX)&HOV','name' => 'Pickup & Delivery', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'CSL'], ['mandatory_scan' => 'POD/DEX07/DRO/PUP/MDE','name' => 'Consolidator', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'MBG'], ['mandatory_scan' => 'MSP/STAT37/DEX37/POD','name' => 'MBG (Damage/Missing)', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'SHH'], ['mandatory_scan' => 'POD','name' => 'SHCP/Handcarry Handling', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'TMK'], ['mandatory_scan' => 'PUP/PUX/POD/DEX07','name' => 'Tagihan Mitra Kurir (Insentif Bulanan)', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'RVN'], ['mandatory_scan' => '','name' => 'Rental Van', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'TLH'], ['mandatory_scan' => 'LTO','name' => 'Trucking Line Haul', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => false,
                'amount_smu'                    => false,
                'amount_awb_smu'                => true,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
            [ ['code' => 'MNL'], ['mandatory_scan' => '','name' => 'Manual', 'columns' => [
                'withholding_tax'               => true,
                'vat_tax'                       => true,
                'product'                       => true,
                'area'                          => true,
                'cost_center'                   => true,
                'route_awb'                     => true,
                'route_smu'                     => false,
                'amount_awb'                    => true,
                'amount_smu'                    => true,
                'amount_awb_smu'                => false,
                'smu'                           => false,
                'awb'                           => true,
                'service'                       => true,
                'delta_weight_smu'              => true,
                'delta_weight_awb'              => true,
                'invoice_weight_smu'            => true,
                'invoice_weight_awb'            => true,
                'sales_channel'                 => true,
                'validation_reference'          => true,
                'validation_weight'             => true,
                'validation_scan_compliance'    => true,
                'validation_ops_plan'           => true,
                'validation_bill'               => true,
            ] ]],
        ];

        foreach($data as $row) {
            Model::updateOrCreate(
                $row[0],
                $row[1],
            );
        }
    }
}
