export default () => {
    return {
        page: {
            module  : 'master',
            name    : 'ops-plans',
            title   : 'Ops Plan'
        },
        form: {
            id: null,

            service_type: null,
            origin_city: null,
            origin_station: null,
            pick_up_served_by: null,
            hub_origin: null,
            scan_origin: null,
            dest_city: null,
            dest_station: null,
            delivery_served_by: null,
            hub_dest: null,
            scan_dest: null,
            is_active: null,
            pick_up_cost: null,
            agent_pickup: null,
            vendor_pickup: null,
            outlet_dropoff: null,
            consolidator_pickup: null,
            shuttle_to_hub_consol_origin: null,
            shuttle_pup_consolagent_origin: null,
            mde: null,
            sorting_origin: null,
            handover_to_vendor_origin: null,
            shuttle_origin: null,
            trucking_firstmile_rpx: null,
            trucking_firstmile_vendor: null,
            kereta_firstmile: null,
            smu_firstmile: null,
            hub_station_origin: null,
            receive_shipment_origin: null,
            hub_origin_rpx: null,
            hub_origin_vendor: null,
            warehouse_in_edc: null,
            shuttle_penarikan_edc: null,
            sorting_edc: null,
            shuttle_to_ra: null,
            trucking_middlemile: null,
            kereta_middlemile: null,
            smu_middlemile: null,
            hub_station_dest: null,
            receive_shipment_dest: null,
            hub_dest_rpx: null,
            hub_dest_vendor: null,
            warehouse_in_dest: null,
            shuttle_penarikan_dest: null,
            sorting_dest: null,
            rpx_delivery: null,
            shuttle_to_consolagent_dest: null,
            hub_consol_to_consolidator_dest: null,
            consolidator_delivery: null,
            agent_delivery: null,
            vendor_delivery: null,
            outlet_handling_delivery: null,
            excel_file: null,
            created_at: null,
            updated_at: null,
            created_user: null,
            updated_user: null,
        }
    }
}
